graph TD
    A[User] --> B[Next.js App]
    B --> C[Pages]
    B --> D[Components]
    B --> E[API Routes]
    C --> F[Learn]
    C --> G[Use]
    C --> H[Dev]
    F --> I[FAQ]
    F ==> J[Recall]
    G ==> K[Chat]
    G ==> L[Quiz]
    H --> M[Documentation]
    H -.-> X[GitHub Repo]
    D --> N[UI Components]
    D --> O[Themes]
    E --> P[LoadingQuiz]
